'use client'
import { useEffect, useState } from 'react'
import BannerBox from '@/components/shared/BannerBox'
import Link from 'next/link'
import styles from '@shared/styles.module.css'
import TabsComponent, { TabInputs } from '@/components/shared/TabsComponent'
import Send from './SendTab'
import Validate from './ValidateTab'

interface XDREdgeTestContentProps {
  sampleCCDAFiles: string[]
}
const XDREdgeTestContent = ({ sampleCCDAFiles }: XDREdgeTestContentProps) => {
  const [selectedTab, setSelectedTab] = useState('SITE Sends XDR Messages to Your System')

  const XDREdgeTabs: TabInputs[] = [
    {
      tabName: 'SITE Sends XDR Messages to Your System',
      tabIndex: 0,
      tabPanel: <Send sampleCCDAFiles={sampleCCDAFiles} />,
    },
    { tabName: 'Validate XDR Messages Generated by Your System', tabIndex: 1, tabPanel: <Validate /> },
  ]

  useEffect(() => {
    const handleRouteChange = () => {
      const hash = window.location.hash.replace('#', '').replace(/-/g, ' ').toLowerCase()
      const tab = XDREdgeTabs.find((t) => t.tabName.toLowerCase() === hash)
      setSelectedTab(tab ? tab.tabName : 'SITE Sends XDR Messages to Your System')
    }

    handleRouteChange()
    window.addEventListener('hashchange', handleRouteChange)

    return () => {
      window.removeEventListener('hashchange', handleRouteChange)
    }
  })

  return (
    <>
      {/* Global Header */}
      <BannerBox
        breadcrumbs={[
          <Link color="inherit" href="/direct" key="1" className={styles.link}>
            Direct
          </Link>,
          <Link color="inherit" href="/direct/xdr-edge" key="2" className={styles.link}>
            XDR Edge Test Tool
          </Link>,
        ]}
        heading={'Direct XDR Edge Test Tool'}
        description={
          <>
            The goal of the Direct XDR Edge Test Tool is to provide a mechanism for developers to test their Direct Test
            Tools protocols implementation based on IHE XDR profile.
          </>
        }
      />
      {/* Main Content */}
      <TabsComponent selectedTab={selectedTab} tabs={XDREdgeTabs} />
    </>
  )
}

export default XDREdgeTestContent
