const criteria = [
  {
    name: 'Please select',
    xdrTest: false,
    testList: "['h1','h2','b1','su1','sa1','sc2']",
    criteria: "''",
    selectOption: "['A','B','2','3','4','5','6','7','8','9','10']",
  },
  {
    name: 'Paragraph (i) Direct Home - Certificates',
    testList: "['h1']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
  },
  {
    name: 'Paragraph (i) Certificate Discovery / Hosting - 2015 DCDT',
    testList: "['h1']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
  },
  {
    name: 'Paragraph (i) Register Direct',
    testList: "['h1']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
  },
  {
    name: 'Paragraph (i) Send Direct Message',
    testList: "['h1']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
  },
  {
    name: 'Paragraph (i) Receive - Message Status',
    testList: "['h1']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
  },
  {
    name: 'Paragraph (ii) Delivery Notifications',
    xdrTest: false,
    protocol: 'MT',
    testList: "['h1']",
    criteria: "'h1-1'",
    uploadOption: true,
  },
  {
    name: 'Paragraph (i) Certificate Discovery / Hosting - 2015 DCDT',
    testList: "['h2']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
    selectOption: "['A','B','2','9','5','6','10']",
  },
  {
    name: 'Paragraph (i) Register Direct',
    testList: "['h2']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
    selectOption: "['A','B','2','9']",
  },
  {
    name: 'Paragraph (i) Direct Home - Certificates',
    testList: "['h2']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
    selectOption: "['A','B','6','5']",
  },
  {
    name: 'Paragraph (i) Send Direct Message',
    testList: "['h2']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
    selectOption: "['A','B','5','6']",
  },
  {
    name: 'Paragraph (i) Message Status',
    testList: "['h2']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
    selectOption: "['A','B','5','6']",
  },
  {
    name: 'Paragraph (i) C-CDA R2.1 Validator',
    testList: "['h2']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
    selectOption: "['B']",
  },
  {
    name: 'Paragraph (i) XDR Validator',
    testList: "['h2']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
  },
  {
    name: 'Paragraph (i) XDM Validator',
    testList: "['h2']",
    redirect: {
      hrefvalue: '',
      hreflabel: '',
      hrefback: '',
    },
    selectOption: "['2','6','4','B','5']",
  },
  {
    name: 'Paragraph (i)(B) Send conversion XDR',
    xdrTest: true,
    testList: "['h2']",
    criteria: "'h2-1'",
    selectOption: "['3','B']",
  },
  {
    name: 'Paragraph (i)(B)  Receive conversion XDR',
    xdrTest: true,
    testList: "['h2']",
    criteria: "'h2-2'",
    selectOption: "['5','7']",
  },
  {
    name: 'Paragraph (i)(C) Send using Edge Protocol - XDR',
    xdrTest: true,
    testList: "['h2']",
    criteria: "'h2-3'",
    selectOption: "['B','3','4']",
  },
  {
    name: 'Paragraph (i)(C) Send using Edge Protocol - SMTP',
    xdrTest: false,
    protocol: 'SMTP',
    testList: "['h2']",
    criteria: "'h2-13'",
    selectOption: "['B','4']",
  },
  {
    name: 'Paragraph (i)(C) Send using Edge Protocol - Delivery Notification',
    xdrTest: false,
    protocol: 'MT',
    testList: "['h2']",
    criteria: "'h2-4'",
    selectOption: "['B','4']",
  },
  {
    name: 'Paragraph (i)(C) Send using Edge Protocol - IMAP',
    xdrTest: false,
    protocol: 'IMAP',
    testList: "['h2']",
    criteria: "'h2-5'",
    selectOption: "['B','4']",
  },
  {
    name: 'Paragraph (i)(C) Send using Edge Protocol - POP',
    xdrTest: false,
    protocol: 'POP',
    testList: "['h2']",
    criteria: "'h2-6'",
    selectOption: "['B','4']",
  },
  {
    name: 'Paragraph (i)(C) Receive using Edge Protocol - XDR',
    xdrTest: true,
    testList: "['h2']",
    criteria: "'h2-7'",
    selectOption: "['5','8']",
  },
  {
    name: 'Paragraph (i)(C) Receive using Edge Protocol - SMTP',
    xdrTest: false,
    protocol: 'SMTP',
    testList: "['h2']",
    criteria: "'h2-8'",
    selectOption: "['5','8']",
  },
  {
    name: 'Paragraph (ii) Delivery Notification in Direct - SMTP',
    xdrTest: false,
    protocol: 'MT',
    testList: "['h2']",
    criteria: "'h2-9'",
    selectOption: "['9','B']",
  },
  {
    name: 'Paragraph (ii) Receive SMTP: Disposition-Notification',
    xdrTest: false,
    uploadOption: true,
    protocol: 'MT',
    testList: "['h2']",
    criteria: "'h2-10'",
    selectOption: "['5','10']",
  },
  {
    name: 'Paragraph (ii)(C) Delivery Notification in Direct - XDR',
    xdrTest: true,
    testList: "['h2']",
    criteria: "'h2-11'",
    selectOption: "['9','B']",
  },
  {
    name: 'Paragraph (ii)(C) Receive XDR: Disposition-Notification',
    xdrTest: true,
    testList: "['h2']",
    criteria: "'h2-12'",
    selectOption: "['5','10']",
  },
  {
    name: 'Paragraph (i)(A) Send using Edge Protocol - XDR',
    xdrTest: true,
    testList: "['b1']",
    criteria: "'b1-1'",
  },
  {
    name: 'Paragraph (i)(A) Send using Edge Protocol - SMTP',
    xdrTest: false,
    protocol: 'SMTP',
    testList: "['b1']",
    criteria: "'b1-8'",
  },
  {
    name: 'Paragraph (i)(A) Send using Edge Protocol - Delivery Notification',
    xdrTest: false,
    protocol: 'MT',
    testList: "['b1']",
    criteria: "'b1-2'",
  },
  {
    name: 'Paragraph (i)(B) Receive using Edge Protocol - XDR',
    xdrTest: true,
    testList: "['b1']",
    criteria: "'b1-3'",
  },
  {
    name: 'Paragraph (i)(B) Receive using Edge Protocol - SMTP',
    xdrTest: false,
    protocol: 'SMTP',
    testList: "['b1']",
    criteria: "'b1-4'",
  },
  {
    name: 'Paragraph (i)(B) Receive using Edge Protocol - IMAP',
    xdrTest: false,
    protocol: 'IMAP',
    testList: "['b1']",
    criteria: "'b1-5'",
  },
  {
    name: 'Paragraph (i)(B) Receive using Edge Protocol - POP3',
    xdrTest: false,
    protocol: 'POP',
    testList: "['b1']",
    criteria: "'b1-6'",
  },
  {
    name: 'Paragraph (i)(C) XDM Processing(Received via Edge Protocol)',
    xdrTest: false,
    protocol: 'SMTP',
    testList: "['b1']",
    criteria: "'b1-7'",
  },

  {
    name: 'Paragraph (i)(A) Send using Edge Protocol - XDR',
    xdrTest: true,
    testList: "['su1']",
    criteria: "'su1-1'",
  },
  {
    name: 'Paragraph (i)(A) Send using Edge Protocol - Delivery Notification',
    xdrTest: false,
    protocol: 'MT',
    testList: "['su1']",
    criteria: "'su1-2'",
  },
  {
    name: 'Paragraph (i)(B) Receive using Edge Protocol - XDR',
    xdrTest: true,
    testList: "['su1']",
    criteria: "'su1-3'",
  },
  {
    name: 'Paragraph (i)(B) Receive using Edge Protocol - SMTP',
    xdrTest: false,
    protocol: 'SMTP',
    testList: "['su1']",
    criteria: "'su1-4'",
  },
  {
    name: 'Paragraph (i)(B) Receive using Edge Protocol - IMAP',
    xdrTest: false,
    protocol: 'IMAP',
    testList: "['su1']",
    criteria: "'su1-5'",
  },
  {
    name: 'Paragraph (i)(B) Receive using Edge Protocol - POP3',
    xdrTest: false,
    protocol: 'POP',
    testList: "['su1']",
    criteria: "'su1-6'",
  },
  {
    name: 'Paragraph (i)(C) XDM Processing(Received via Edge Protocol)',
    xdrTest: false,
    protocol: 'SMTP',
    testList: "['su1']",
    criteria: "'su1-7'",
  },
  {
    name: 'Paragraph (i) Direct Home - Certificates',
    testList: "['sa1']",
    redirect: {
      hrefvalue: 'direct.home',
      hreflabel: '170.315(h)(1)',
      hrefback: 'surveillance.surveilh1.main',
    },
  },
  {
    name: 'Paragraph (i) Certificate Discovery / Hosting - 2015 DCDT',
    testList: "['sa1']",
    redirect: {
      hrefvalue: 'direct.dcdt2',
      hreflabel: '170.315(h)(1)',
      hrefback: 'surveillance.surveilh1.main',
    },
  },
  {
    name: 'Paragraph (i) Register Direct',
    testList: "['sa1']",
    redirect: {
      hrefvalue: 'direct.register',
      hreflabel: '170.315(h)(1)',
      hrefback: 'surveillance.surveilh1.main',
    },
  },
  {
    name: 'Paragraph (i) Send Direct Message',
    testList: "['sa1']",
    redirect: {
      hrefvalue: 'direct.send',
      hreflabel: '170.315(h)(1)',
      hrefback: 'surveillance.surveilh1.main',
    },
  },
  {
    name: 'Paragraph (i) Receive - Message Status',
    testList: "['sa1']",
    redirect: {
      hrefvalue: 'direct.status',
      hreflabel: '170.315(h)(1)',
      hrefback: 'surveillance.surveilh1.main',
    },
  },
  {
    name: 'Paragraph (ii) Delivery Notifications',
    xdrTest: false,
    protocol: 'MT',
    testList: "['sa1']",
    criteria: "'sa1-1'",
    uploadOption: true,
  },
  {
    name: 'Paragraph (i) Certificate Discovery / Hosting - 2015 DCDT',
    testList: "['sc2']",
    redirect: {
      hrefvalue: 'direct.dcdt2',
      hreflabel: '170.315(h)(2)',
      hrefback: 'surveillance.surveilh2.main',
    },
    selectOption: "['A','B','2','9','5','6','10']",
  },
  {
    name: 'Paragraph (i) Register Direct',
    testList: "['sc2']",
    redirect: {
      hrefvalue: 'direct.register',
      hreflabel: '170.315(h)(2)',
      hrefback: 'surveillance.surveilh2.main',
    },
    selectOption: "['A','B','2','9']",
  },
  {
    name: 'Paragraph (i) Direct Home - Certificates',
    testList: "['sc2']",
    redirect: {
      hrefvalue: 'direct.home',
      hreflabel: '170.315(h)(2)',
      hrefback: 'surveillance.surveilh2.main',
    },
    selectOption: "['A','B','6','5']",
  },
  {
    name: 'Paragraph (i) Send Direct Message',
    testList: "['sc2']",
    redirect: {
      hrefvalue: 'direct.send',
      hreflabel: '170.315(h)(2)',
      hrefback: 'surveillance.surveilh2.main',
    },
    selectOption: "['A','B','5','6']",
  },
  {
    name: 'Paragraph (i) Message Status',
    testList: "['sc2']",
    redirect: {
      hrefvalue: 'direct.status',
      hreflabel: '170.315(h)(2)',
      hrefback: 'surveillance.surveilh2.main',
    },
    selectOption: "['A','B','5','6']",
  },
  {
    name: 'Paragraph (i) C-CDA R2.1 Validator',
    testList: "['sc2']",
    redirect: {
      hrefvalue: 'direct.ccdar2',
      hreflabel: '170.315(h)(2)',
      hrefback: 'surveillance.surveilh2.main',
    },
    selectOption: "['B']",
  },
  {
    name: 'Paragraph (i) XDR Validator',
    testList: "['sc2']",
    redirect: {
      hrefvalue: 'validators.xdr',
      hreflabel: '170.315(h)(2)',
      hrefback: 'surveillance.surveilh2.main',
    },
  },
  {
    name: 'Paragraph (i) XDM Validator',
    testList: "['sc2']",
    redirect: {
      hrefvalue: 'validators.xdm',
      hreflabel: '170.315(h)(2)',
      hrefback: 'surveillance.surveilh2.main',
    },
    selectOption: "['2','6','4','B','5']",
  },
  {
    name: 'Paragraph (i)(B) Send conversion XDR',
    xdrTest: true,
    testList: "['sc2']",
    criteria: "'sc2-1'",
    selectOption: "['3','B']",
  },
  {
    name: 'Paragraph (i)(B)  Receive conversion XDR',
    xdrTest: true,
    testList: "['sc2']",
    criteria: "'sc2-2'",
    selectOption: "['5','7']",
  },
  {
    name: 'Paragraph (i)(C) Send using Edge Protocol - XDR',
    xdrTest: true,
    testList: "['sc2']",
    criteria: "'sc2-3'",
    selectOption: "['B','3','4']",
  },
  {
    name: 'Paragraph (i)(C) Send using Edge Protocol - SMTP',
    xdrTest: false,
    protocol: 'MT',
    testList: "['sc2']",
    criteria: "'sc2-4'",
    selectOption: "['B','4']",
  },
  {
    name: 'Paragraph (i)(C) Receive using Edge Protocol - XDR',
    xdrTest: true,
    testList: "['sc2']",
    criteria: "'sc2-7'",
    selectOption: "['5','8']",
  },
  {
    name: 'Paragraph (i)(C) Receive using Edge Protocol - SMTP',
    xdrTest: false,
    protocol: 'SMTP',
    testList: "['sc2']",
    criteria: "'sc2-8'",
    selectOption: "['5','8']",
  },
  {
    name: 'Paragraph (ii) Delivery Notification in Direct - SMTP',
    xdrTest: false,
    protocol: 'MT',
    testList: "['sc2']",
    criteria: "'sc2-9'",
    selectOption: "['9','B']",
  },
  {
    name: 'Paragraph (ii) Receive SMTP: Disposition-Notification',
    xdrTest: false,
    uploadOption: true,
    protocol: 'MT',
    testList: "['sc2']",
    criteria: "'sc2-10'",
    selectOption: "['5','10']",
  },
  {
    name: 'Paragraph (ii)(C) Delivery Notification in Direct - XDR',
    xdrTest: true,
    testList: "['sc2']",
    criteria: "'sc2-11'",
    selectOption: "['9','B']",
  },
]

export default criteria
